fix: Fix the threeshold of the benchmark accuracy

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -47,9 +47,9 @@ jobs:
         OUTPUT=$(./build/benchmarks)
         echo "$OUTPUT"
         
-        if echo "$OUTPUT" | grep "RMS" | awk '{ if ($2 > 10) exit 1 }'; then
+        if echo "$OUTPUT" | grep "RMS" | awk '{ if ($2 > 20) exit 1 }'; then
           echo "Complexity RMS check passed."
         else
-          echo "Complexity RMS check failed (exceeded 10% threeshold)!"
+          echo "Complexity RMS check failed (exceeded 20% threeshold)!"
           exit 1
         fi
